### PR TITLE
Fix: setContext doesn't trigger componentWillReceiveProps 

### LINKED ISSUE #2258: setContext doesn't trigger componentWillReceiveProps
### Current behavior

`setContext` doesn't trigger `componentWillReceiveProps`

### Expected behavior

`setContext` should trigger `componentWillReceiveProps`.

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.10.0
| react               | 16.3.18
| react-dom           | 16.3.3
| react-test-renderer | 16.10.2
| adapter (below)     | 1.14.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

### PR DESCRIPTION
**Pull request by mul53**
Fixes #2258

Below are two code sandboxes that show the bug exists, i added enzyme to the sandbox when you run the tests sandbox 2 doesn't call the method while sandbox 1 does.
-  [Sandbox #1](https://codesandbox.io/s/distracted-sun-8vqh9) enzyme 3.3.0, react 16.14.0
-  [Sandbox #2](https://codesandbox.io/s/lucid-wilbur-wkotf) enzyme 3.4.0, react 16.0.0

### CODE REVIEW

**Comment by mul53** [comment]
@ljharb  Here are the sandboxes

[React 0.14 Sandbox](https://codesandbox.io/s/setcontext-react-014-jhwel)
[React 15 Sandbox](https://codesandbox.io/s/setcontext-react-15-wirdb)
[React 16.2 Sandbox](https://codesandbox.io/s/setcontext-react-162-wg51l)
[React 16.3 Sandbox](https://codesandbox.io/s/setcontext-react-163-n757b)
[React 16.4 Sandbox](https://codesandbox.io/s/setcontext-react-164-ww626)

I will continue looking at the issue

File: packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js [hunk 1]
```diff
@@ -23,7 +23,9 @@ import {
   getNodeFromRootFinder,
   wrapWithWrappingComponent,
   getWrappingComponentMountRenderer,
+  spyMethod,
 } from 'enzyme-adapter-utils';
```
Comment (ljharb) [inline packages/enzyme-adapter-react-14/src/ReactFourteenAdapter.js:27]: I ended up adding spyMethod/spyProperty to enzyme-adapter-utils, so that the adapters didn't have to suddenly start requiring enzyme v3.4.0.

**Review by ljharb — APPROVED** [review]
